[package]
name = "wff"
version = "0.1.0"
authors = ["Timothy Goodwin <tim4262244@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
multimap = "0.8.0"
